### ISSUE TITLE
MolPickler doesn't preserve atom properties

### ISSUE THREAD

**Issue by gedeck** [rdkit/rdkit#1320]
```
from rdkit import Chem
mol = Chem.RWMol(Chem.MolFromSmiles('CCC'))
mol.GetAtomWithIdx(0).SetProp('label', 'X')
atom = mol.GetAtomWithIdx(0)
print(atom.HasProp('label'), atom.GetProp('label'))
mol = Chem.Mol(mol.ToBinary())
atom = mol.GetAtomWithIdx(0)
print(atom.HasProp('label'))
```
gives
```
1 X
0
```

It could be that there is a flag to preserve the atom properties. If that is the case, an improvement of the docs would be required. PropertyMol also doesn't preserve the atom properties.

**Comment by greglandrum** [comment]
This was resolved by #1277 : it's now possible to configure the RDKit to pickle molecular, atomic, and bond properties:
```
In [14]: m.SetProp('foo','bar')

In [16]: m.GetAtomWithIdx(0).SetIntProp('hello',4)

In [17]: Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)

In [18]: import pickle

In [19]: m2 = pickle.loads(pickle.dumps(m))

In [20]: m2.GetPropsAsDict()
Out[20]: {'foo': 'bar', 'numArom': 0}

In [21]: m2.GetAtomWithIdx(0).GetPropsAsDict()
Out[21]: {'_CIPRank': 0, 'hello': 4}

In [22]: m2 = Chem.Mol(m.ToBinary())

In [23]: m2.GetPropsAsDict()
Out[23]: {'foo': 'bar', 'numArom': 0}

In [24]: m2.GetAtomWithIdx(0).GetPropsAsDict()
Out[24]: {'_CIPRank': 0, 'hello': 4}
```

Note that the default behavior is the same as before, you do need to set the option in order to have properties pickled with the molecule.

**Comment by mwojcikowski** [comment]
I'm still having an issue with the pickler - the chirality is lost. See example:
```
In [3]: mol = Chem.MolFromSmiles('CN[C@@H](C)C(=O)N[C@H](C(=O)N1C[C@@H](Oc2ccccc2)C[C@H]1C(=O)N[C@@H]1CCCc2ccccc21)C1CCCCC1')

In [4]: Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)

In [6]: Chem.MolToSmiles(mol)
Out[6]: 'CNC(C)C(=O)NC(C(=O)N1CC(Oc2ccccc2)CC1C(=O)NC1CCCc2ccccc21)C1CCCCC1'

In [7]: Chem.MolToSmiles(mol, isomericSmiles=True)
Out[7]: 'CN[C@@H](C)C(=O)N[C@H](C(=O)N1C[C@@H](Oc2ccccc2)C[C@H]1C(=O)N[C@@H]1CCCc2ccccc21)C1CCCCC1'

In [8]: import pickle

In [9]: mol2 = pickle.loads(pickle.dumps(mol))

In [10]: Chem.MolToSmiles(mol2, isomericSmiles=True)
Out[10]: 'CNC(C)C(=O)NC(C(=O)N1CC(Oc2ccccc2)CC1C(=O)NC1CCCc2ccccc21)C1CCCCC1'

```

**Comment by greglandrum** [comment]
hmm, this is an interesting one:
```
In [1]: from rdkit import Chem

In [2]: mol = Chem.MolFromSmiles('CN[C@@H](C)C(=O)N[C@H](C(=O)N1C[C@@H](Oc2ccccc2)C[C@H]1C(=O)N[C@@H]1CCCc2ccccc21)C1CCCCC1')

In [3]: import pickle

In [4]: Chem.MolToSmiles(pickle.loads(pickle.dumps(mol)),isomericSmiles=True)
Out[4]: 'CN[C@@H](C)C(=O)N[C@H](C(=O)N1C[C@@H](Oc2ccccc2)C[C@H]1C(=O)N[C@@H]1CCCc2ccccc21)C1CCCCC1'

In [5]: Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)

In [6]: Chem.MolToSmiles(pickle.loads(pickle.dumps(mol)),isomericSmiles=True)
Out[6]: 'CNC(C)C(=O)NC(C(=O)N1CC(Oc2ccccc2)CC1C(=O)NC1CCCc2ccccc21)C1CCCCC1'
```
This is, almost certainly, a bug. @bp-kelley ?

**Comment by bp-kelley** [comment]
It's a bug.  I'm unsure what is going on but will sort it out.

**Comment by bp-kelley** [comment]
Something is screwy with pickling the Bond properties and stereo info.  The following currently is doing the right thing if it helps at all.  I'll keep investigating.

Chem.SetDefaultPickleProperties(
                                Chem.PropertyPickleOptions.MolProps |
                                Chem.PropertyPickleOptions.AtomProps |
#                                Chem.PropertyPickleOptions.BondProps )
                                Chem.PropertyPickleOptions.PrivateProps |
                                Chem.PropertyPickleOptions.ComputedProps)

**Comment by mwojcikowski** [comment]
I think I've found it - the BondProps and QueryAtomProps have the same value (`0x100`), see https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/MolPickler.h#L50-L51

**Comment by bp-kelley** [comment]
@mwojcikowski That's certainly a bug, but the problem is elsewhere.  I believe that I'm not pickling enough property types.  Working on it.

**Comment by mwojcikowski** [comment]
Ping. (as Greg suggested).

Is there any progress with the MolPickler?

**Comment by bp-kelley** [comment]
It has been fixed!  There was a deeper problem that needed to be resolved, but the next release resolves the issue.

----
Brian Kelley

**Comment by greglandrum** [comment]
Yeah, this should have been taken care of by #1541 
We forgot to reference the issue.

**Comment by hjuinj** [comment]
how can I pickle a list of mols while preserving properties?
I can pickle list of mols before if I do not do `Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)`,
Once I set this I then get `ValueError: invalid BitVect pickle` when I try to load the list (dumping outputs no error)

**Comment by bp-kelley** [comment]
@hjuinj could you file an issue with an example?  I’ll try to reproduce the issue, but this is probably the wrong bug report for this.

**Comment by hjuinj** [comment]
@bp-kelley sorry, false alarm. I found out it is not a problem of pickling a list of mols. There is one molecule in my list that is somehow bogus and if I pickle it after `Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)` I get the aforementioned error once I try to load it.

However, if I dump it without saving any properties, then load this molecule, then dump it again with `Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)` first, everything works fine... Therefore I don't know what I can provide to reproduce this error remotely... Furthermore, I think this is more due to the messed-up-ness of my molecules (mols constructed from xyz files) rather than issues with rdkit so this is probably not worth-while chasing after. Sorry again for the false alarm.

**Comment by bp-kelley** [comment]
@hjuinj that doesn’t sound quite right.  If you can share the input dataset is love to look at it.
