### ISSUE TITLE
Atom index out of range error

### ISSUE THREAD

**Issue by A-Thakkar** [rdkit/rdkit#1868]
Converting RXN blocks into reaction smiles via an rdkit reaction, the atom index is out of range. This seems to occur randomly, as multiple attempts on the same reaction block show that it may indeed be converted. 
The getIdx() method seems to be retrieving atomic indexes way beyond those that should be in the created molecule.  

https://github.com/rdkit/rdkit/blob/2190c991f03d44d0df1fd22b372ca85036074301/Code/GraphMol/ROMol.cpp#L158

**Comment by bp-kelley** [comment]
We’ll need the rxn block to diagnose this one.

**Comment by A-Thakkar** [comment]
I've attached one such rxn block which causes the error
[error.txt](https://github.com/rdkit/rdkit/files/2004984/error.txt)

**Comment by andy-d-palmer** [comment]
Hi @A-Thakkar and @bp-kelley, was any progress made on this issue? I am able to reproduce it using the latest conda-forge python binaries and the [v3kAmideBond.rxn](https://github.com/rdkit/rdkit/blob/6224a42516fa47806e135f23c34eacaf014824f1/Code/GraphMol/ChemReactions/testData/v3k.AmideBond.rxn) file. 

As @A-Thakkar reported, the issue seems somewhat random, and sometimes the code will run sucessfully.

Code to reproduce: 
```
from rdkit.Chem import AllChem
from rdkit.Chem import MolToSmiles
_rxn = AllChem.ReactionFromRxnFile('v3k.AmideBond.rxn')
_reacts = [MolToSmiles(r) for r in _rxn.GetReactants()]
_prods = [MolToSmiles(p) for p in _rxn.GetProducts()]
_reacts, _prods
```
Traceback:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-592d4f2a0a09> in <module>
      2 from rdkit.Chem import MolToSmiles
      3 _rxn = AllChem.ReactionFromRxnFile('v3k.AmideBond.rxn')
----> 4 _reacts = [MolToSmiles(r) for r in _rxn.GetReactants()]
      5 _prods = [MolToSmiles(p) for p in _rxn.GetProducts()]
      6 _reacts, _prods

<ipython-input-3-592d4f2a0a09> in <listcomp>(.0)
      2 from rdkit.Chem import MolToSmiles
      3 _rxn = AllChem.ReactionFromRxnFile('v3k.AmideBond.rxn')
----> 4 _reacts = [MolToSmiles(r) for r in _rxn.GetReactants()]
      5 _prods = [MolToSmiles(p) for p in _rxn.GetProducts()]
      6 _reacts, _prods

RuntimeError: Range Error
	idx
	Violation occurred on line 174 in file Code/GraphMol/ROMol.cpp
	Failed Expression: 22052 < 1
	RDKIT: 2019.03.2
	BOOST: 1_70
```

**Comment by bp-kelley** [comment]
Apologies, this fell off my radar.  I’ll take a look on the next few days.

**Comment by bp-kelley** [comment]
I can reliably get this code to fail, and it does appear to one a bit random:

```
for i in range(1000):
    print(i)
    _rxn = AllChem.ReactionFromRxnFile('v3kAmideBond.rxn')
    _reacts = [MolToSmiles(r) for r in _rxn.GetReactants()]
    _prods = [MolToSmiles(p) for p in _rxn.GetProducts()]
    print (_reacts, _prods)
```

**Comment by bp-kelley** [comment]
I think this has been fixed recently, I've added test for the above bug and hopefully it has been squashed.

**Comment by greglandrum** [comment]
I just tried on my windows machine with the current status of master and I am able to reproduce the bug intermittently, so it's definitely not fixed.
Looks like this is a job for valgrind

**Comment by glauco-endrigo** [comment]
Hi, is the problem solved? Im facing the same issue: molecule.

GetAtomWithIdx(12)

[08:19:18] 

****
Range Error
idx
Violation occurred on line 206 in file /project/build/temp.linux-x86_64-cpython-39/rdkit/Code/GraphMol/ROMol.cpp
Failed Expression: 12 < 12
****

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [57], in <cell line: 1>()
----> 1 molecule.GetAtomWithIdx(12)

RuntimeError: Range Error
	idx
	Violation occurred on line 206 in file Code/GraphMol/ROMol.cpp
	Failed Expression: 12 < 12
	RDKIT: 2022.03.1
	BOOST: 1_75
