### ISSUE TITLE
Segmentation fault occurs when pybel is imported before RDKit

### ISSUE THREAD

**Issue by n-yoshikawa** [rdkit/rdkit#2292]
I am not sure which of Open Babel and RDKit causes this problem, so I crosspost to both projects. (openbabel/openbabel#1938)

## Environment Information
Open Babel version: 2.4.1 (installed by anaconda)
RDKit version: 2018.09.1 (installed by anaconda)
Operating system and version: Ubuntu 18.04

## Expected Behavior
No segmentation fault occurs when pybel is imported before RDKit.

## Actual Behavior
Segmentation fault occurs.

## Steps to Reproduce
This code is from [3D functionality in the RDKit](https://rdkit.org/docs/Cookbook.html#d-functionality-in-the-rdkit) in RDKit Cookbook.

This code has no problem. (You can get `1DWD_ligand.pdb` and `1PPC_ligand.pdb` from [here](https://github.com/rdkit/rdkit/tree/master/rdkit/Chem/test_data))
```python
from rdkit import Chem, RDConfig
from rdkit.Chem import AllChem, TorsionFingerprints

import pybel

ref = Chem.MolFromSmiles(
    'NC(=[NH2+])c1ccc(C[C@@H](NC(=O)CNS(=O)(=O)c2ccc3ccccc3c2)C(=O)N2CCCCC2)cc1')
mol1 = Chem.MolFromPDBFile('1DWD_ligand.pdb')
mol1 = AllChem.AssignBondOrdersFromTemplate(ref, mol1)
mol2 = Chem.MolFromPDBFile('1PPC_ligand.pdb')
mol2 = AllChem.AssignBondOrdersFromTemplate(ref, mol2)
tfd1 = TorsionFingerprints.GetTFDBetweenMolecules(mol1, mol2)
tfd2 = TorsionFingerprints.GetTFDBetweenMolecules(mol1, mol2, useWeights=False)
tfd3 = TorsionFingerprints.GetTFDBetweenMolecules(mol1, mol2, maxDev='spec')
print(tfd1, tfd2, tfd3)
```

This code fails with segmentation fault.
```python
import pybel

from rdkit import Chem, RDConfig
from rdkit.Chem import AllChem, TorsionFingerprints

ref = Chem.MolFromSmiles(
    'NC(=[NH2+])c1ccc(C[C@@H](NC(=O)CNS(=O)(=O)c2ccc3ccccc3c2)C(=O)N2CCCCC2)cc1')
mol1 = Chem.MolFromPDBFile('1DWD_ligand.pdb')
mol1 = AllChem.AssignBondOrdersFromTemplate(ref, mol1)
mol2 = Chem.MolFromPDBFile('1PPC_ligand.pdb')
mol2 = AllChem.AssignBondOrdersFromTemplate(ref, mol2)
tfd1 = TorsionFingerprints.GetTFDBetweenMolecules(mol1, mol2)
tfd2 = TorsionFingerprints.GetTFDBetweenMolecules(mol1, mol2, useWeights=False)
tfd3 = TorsionFingerprints.GetTFDBetweenMolecules(mol1, mol2, maxDev='spec')
print(tfd1, tfd2, tfd3)
```

Similar problem is reported by rdkit/rdkit#747, but it does not seem to be resolved.

**Comment by bp-kelley** [comment]
I expect this is happening due to incompatibilities in a 3rd party library,
namely boost.  If pybel is built with a different version of boost than the
RDKit you are going to have a bad time.

The first version loads the correct version of boost for rdkit (and the
wrong one for pybel) and the second loads the correct version for pybel
(and the wrong version for rdkit).

My take is that unless you build both yourself with the same boost library,
or ensure they are using the same version of boost, this is a problem
without a solution.

**Comment by n-yoshikawa** [comment]
Thank you for your comment.

This issue is already solved by openbabel/openbabel#1775.

**Comment by msteijaert** [comment]
This problem still occurs if you install both rdkit and openbabel with conda (even if you install the latest versions of both from the conda-forge channel). Did anyone find a solution for this with conda, or is it necessary to build both packages from source?
